# Generated by Django 3.0.8 on 2020-12-22 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_data', '0016_auto_20201206_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='suitable',
            field=models.IntegerField(default=0),
        ),
    ]
